### ISSUE TITLE
country ids filter

### ISSUE THREAD

**Issue by mymtw** [ThalosES/vinted-rs#112]
is it possible to filter by country and order=newest_first in same query

`https://www.vinted.es/catalog?time=1727132656&catalog[]=1904&order=newest_first&search_text=&page=1&country_ids=7`

as I can see it not filtering by country id

**Comment by 0xCAB0** [comment]
We currently support both query parameters

https://github.com/ThalosES/vinted-rs/blob/dfd7ca2a35a87672f22c11577364f1ecb8e6275e/src/queries.rs#L645

https://github.com/ThalosES/vinted-rs/blob/dfd7ca2a35a87672f22c11577364f1ecb8e6275e/src/queries.rs#L683

Please, if clarify more the question for further detail.
Thank you.

**Comment by mymtw** [comment]
@0xCAB0 
could you try this query for api of them?

`https://www.vinted.es/api/v2/catalog/items?catalog_ids=0&country_ids=7&order=newest_first`

e.g. I opened 2nd ad:

![image](https://github.com/user-attachments/assets/d31a3d72-aecd-4425-a205-9e1fdf86d9cb)

`https://www.vinted.es/items/5129184355-robe-courte`

![image](https://github.com/user-attachments/assets/1015fe7c-b0d2-4a67-9219-117da3abd21c)

is api of vinted not filtering by country id? don't you know?

**Comment by 0xCAB0** [comment]
We were aware that the filter is not properly implemented by Vinted, feel free to add a comment to the documentation for everyone to notice.
TY
