### ISSUE TITLE
Private field on AdvancedUser

### ISSUE THREAD

**Issue by LelouchFR** [ThalosES/vinted-rs#80]
I'm trying to access the username and his photo, but I can't, since they are not public, is there a way to access them, or is it possible to make them public in the next version to be able to work with these datas?

```rs
error[E0449]: visibility qualifiers are not permitted here
 --> src/main.rs:7:5
  |
7 |     pub fn get_login(&self) -> &str;
  |     ^^^
  |
  = note: trait items always share the visibility of their trait

error[E0449]: visibility qualifiers are not permitted here
  --> src/main.rs:11:5
   |
11 |     pub fn get_login(&self) -> &str {
   |     ^^^
   |
   = note: trait items always share the visibility of their trait

error[E0616]: field `login` of struct `AdvancedUser` is private
  --> src/main.rs:12:15
   |
12 |         &self.login
   |               ^^^^^ private field

```

wanted behavior:
```rs
trait UserLogin {
    pub fn get_login(&self) -> &str;
}

impl UserLogin for vinted_rs::model::user::AdvancedUser {
    pub fn get_login(&self) -> &str {
        &self.login
    }
}

// then advanced.user.get_login() to get username
```

**Comment by pxp9** [comment]
Could @0xCAB0 or @LelouchFR make a PR modifying these lines ?

https://github.com/ThalosES/vinted-rs/blob/main/src%2Fmodel%2Fuser.rs#L20-L49

**Comment by 0xCAB0** [comment]
Hey! Thanks for reaching out.

We build this library to serve one of our internal projects so we only made public the fields that we needed to interact with.
I will modify all Advanced user and user fields to be public, if you think you may need to use any field in other models, feel free to make them public in this PR.

**Comment by LelouchFR** [comment]
if you want, I can do all this, so you don't have to deep dive again in the code, I've done a lot of things already with it, so I think I can help it to go forward

**Comment by 0xCAB0** [comment]
Checkout the PR, I'm just going to add some extra documentation on the fields

**Comment by 0xCAB0** [comment]
I'm done adding more docs, I'm gonna merge this PR to develop, if you want to add more of your changes please open a different one **to develop** with:
- ft/$github_user/PR_NAME for Features
- fix/$github_user/PR_NAME for Bugfixes
